run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: false
issues:
  exclude-dirs:
    - mocks
    - lib/http/middlewares/authorization/api_test
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    #- exportloopref The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - sloglint
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wrapcheck
    - wsl
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        db: snake
  cyclop:
    max-complexity: 15
    skip-tests: true
  lll:
    line-length: 150
  funlen:
    lines: 80
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(project_sem)
      - default
  gofumpt:
    module-path: project_sem
  sloglint:
    context: "scope"
  nolintlint:
    require-explanation: true
  gosec:
    excludes:
      - G115
  wrapcheck:
    ignoreSigs:
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Errorf(
      - serr.New(
      - serr.Wrap(
