version: '3'

volumes:
  pg_data:

networks:
  app:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  backend:
    build: ./
    env_file: .env
    networks:
      - app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
